### PR TITLE
Fixes #176 issue

### LINKED ISSUE #176: void* userdata in rviRegisterService() points to stack
When debugging an issue with the RVI mode of aktualizr, I ran into a bug where the rvi callbacks were not working correctly.  I think the problem is with the following piece of code that registers the service callbacks:

https://github.com/advancedtelematic/aktualizr/blob/master/src/sotarviclient.cc#L60

rviRegisterService takes a void* pointer for 'user data', but in this case this pointer is shared among every iteration of the loop, and also on the stack.

One solution might be to split callbackWrapper into one function for each of "notify", "start", "chunk", "finish", "getpackages", "abort", and make userdata a pointer to the SotaRVIClient object.  I'm sure there are nicer solutions too :)

### PR DESCRIPTION
**Pull request by patriotyk**
Please check this fix, because I was not able to setup rvi server.

### CODE REVIEW

**Comment by leon-anavi** [comment]
Thank you for the provided fix. It seems that this patch fixes the issue with the registering the services. 

Best regards,
Leon

File: src/sotarviclient.cc [hunk 1]
```diff
@@ -10,11 +10,11 @@
 #include "types.h"
 
 char service_names[6][12] = {"notify", "start", "chunk", "finish", "getpackages", "abort"};
+SotaRVIClient *client;
```
Comment (cajun-rat) [inline src/sotarviclient.cc]: This is OK as a quick-fix, but I'm really not keen on global variables.

**Comment by cajun-rat** [comment]
Please remember to run 'make qa' to reformat to normalised style :)
